export const DATA_TOO_LARGE_DISPLAY = 'DATA_TOO_LARGE_DISPLAY';
export const DATA_TOO_LARGE_TO_COMPUTE = 'DATA_TOO_LARGE_TO_COMPUTE';
export const BAD_REQUEST = 'BAD_REQUEST';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
export const NO_DATA = 'NO_DATA';
